### ISSUE TITLE
With the last spotify update, the text is always gray, and I really do not like how it looks!

### ISSUE THREAD

**Issue by ferNayeon** [JulienMaille/spicetify-dynamic-theme#94]
**Describe the bug**
Before this last Spotify version (Spotify Windows (64 bits)
1.2.48.405.gf2c48e6f), when playing a song with DefaultDynamic, the text would also change color. Now it always looks gray no matter what you do. I have my DefaultDynamic instaled manually, btw.

**Screenshots**
![Captura de pantalla (2872)](https://github.com/user-attachments/assets/2ea973c2-7d9a-49c2-946f-79eaa9a5de6b)
![Captura de pantalla (2873)](https://github.com/user-attachments/assets/b9ba2e2a-397f-4387-a0a2-4b43a4f73ea2)

**Desktop Setup**
Spotify Windows (64 bits)
1.2.48.405.gf2c48e6f
Spicetify v2.38.4
- Theme: DefaultDynamic

**Logs**

![imagen](https://github.com/user-attachments/assets/3be7026b-52ef-4825-b1ad-24fe203d22fa)

**Comment by JulienMaille** [comment]
Thanks for reporting it, I was still on an older version of Spotify. I think I fixed it with latest commit

**Comment by ferNayeon** [comment]
> Thanks for reporting it, I was still on an older version of Spotify. I think I fixed it with latest commit

Thanks a lot for answering! Now, I did update DefaultDynamic from marketplace (it did show me that its last update was today) but the text still shows up gray for me ;( I hope you can fix it, becuase it is the main reason I use spicetify in first place!

**Comment by JulienMaille** [comment]
Usually it takes 24h for github cache to expire and the marketplace to really serve the new code. Let's try tomorrow

**Comment by ferNayeon** [comment]
Okok, thank you so so much. 🙏🏼

**Comment by ferNayeon** [comment]
Hey! It updated. It looks amazing, thank you very very much, it's solved!
Now this is my first time using Github, should I close the thread now? hahah
